/******************************************************************************************************************************
* Name - CVException

* Description - This class does the following:
	- Custom exception class for APTTUS customization.

* Modification Log :
* ---------------------------------------------------------------------------
* Developer Date Description
* ---------------------------------------------------------------------------
* Siva Gunda 10/13/2015 Created.
******************************************************************************************************************************/

public class CVException extends Exception {

}